---
title: "Bash Tutorial"
author: "Chris Mantegna"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    toc: yes
  theme: cerulean
  highlight:
    toc: yes
    toc_float: yes
    number_sections: yes
    code_folding: show
    code_download: yes
    callout-appearance: default
  html_document: null
subtile: Week 01
---
```{r setup, include=FALSE}
# this is just here to remind me what I'm doing
knitr::opts_chunk$set(
  highlight = TRUE,    # Highlight code
  echo = TRUE,         # Display code chunks
  eval = FALSE,        # Evaluate code chunks
  warning = TRUE,     # Hide warnings
  message = TRUE,     # Hide messages
  fig.width = 6,       # Set plot width in inches
  fig.height = 4,      # Set plot height in inches
  fig.align = "center" # Align plots to the center
  )
```

# Must download this file before getting started: <https://d.pr/f/BDaGTy>. I downloaded from the course page and unzipped, placed in data file for coursework repo.

```{bash}

pwd 

```

# unzipped and pulled from local machine. verifying files exist

```{bash}

cd ../data/data-shell/data-shell
ls

```

```{bash}

whoami

```

```{bash}

pwd

```

# Moving back to the directory that has my data file per the exercise directions

```{bash}

cd /home/shared/8TB_HDD_02/cnmntgna/GitHub/chris-coursework1/data/data-shell/data-shell
ls

```

# 

```{bash}

cd /home/shared/8TB_HDD_02/cnmntgna/GitHub/chris-coursework1/data/data-shell/data-shell
ls -F

```

```{bash}

 ls -F data-shell

```

```{bash}

 ls -F /data-shell

```

# I've only had success with the full path

```{bash}

cd /home/shared/8TB_HDD_02/cnmntgna/GitHub/chris-coursework1/data/data-shell/data-shell
ls -F

```

```{bash}

 ls ../data-shell/north-pacific-gyre/2012-07-03/

```

```{bash}

 ls /home/shared/8TB_HDD_02/cnmntgna/GitHub/chris-coursework1/data/data-shell/data-shell/north-pacific-gyre/2012-07-03/

```

```{bash}

cd ../data/data-shell/data-shell
ls -F

```

```{bash}

mkdir thesis

```

```{bash}

ls -F
```

```{bash}

mv thesis/ ../data/data-shell/data-shell
ls -F

```

```{bash}

cd ../data/data-shell/data-shell
ls -F

```

```{bash}

cd /thesis

```

# since that wasn't enough path for the computer to follow me, i added this to get to the desired location

```{bash}

cd ../data/data-shell/data-shell/thesis
ls

```

#did this directly in terminal

```{bash}

cd ../data/data-shell/data-shell/thesis
nano draft.txt

```

the desired location

```{bash}

cd ../data/data-shell/data-shell
 ls

```

# i put it in the wrong directory and have to move it

```{bash}

mv /home/shared/8TB_HDD_02/cnmntgna/GitHub/chris-coursework1/data/data-shell/data-shell/draft.text ../data/data-shell/data-shell/thesis

```

```{bash}

cd ../data/data-shell/data-shell/thesis
 ls

```

# note sure why i move between directories but never seem to stay there, do i have to set my working directory out of the code directory?

```{bash}

rm draft.txt
ls

```

```{bash}

cd /home/shared/8TB_HDD_02/cnmntgna/GitHub/chris-coursework1/data/data-shell/data-shell/molecules

ls 

```

# Adding the text from the assignment to remind myself of the tool: "Let's go into that directory with cd and run the command wc *.pdb. wc is the "word count" command: it counts the number of lines, words, and characters in files. The*  in *.pdb matches zero or more characters, so the shell turns* .pdb into a complete list of .pdb files"

```{bash}

cd /home/shared/8TB_HDD_02/cnmntgna/GitHub/chris-coursework1/data/data-shell/data-shell/molecules

wc *.pdb

```

```{bash}

cd /home/shared/8TB_HDD_02/cnmntgna/GitHub/chris-coursework1/data/data-shell/data-shell/molecules

wc -l *.pdb

```

```{bash}

cd /home/shared/8TB_HDD_02/cnmntgna/GitHub/chris-coursework1/data/data-shell/data-shell/molecules

wc -l *.pdb > lengths

```

```{bash}
cd /home/shared/8TB_HDD_02/cnmntgna/GitHub/chris-coursework1/data/data-shell/data-shell/molecules

ls lengths

```

```{bash}

cd /home/shared/8TB_HDD_02/cnmntgna/GitHub/chris-coursework1/data/data-shell/data-shell/molecules

cat lengths

```

```{bash}

cd /home/shared/8TB_HDD_02/cnmntgna/GitHub/chris-coursework1/data/data-shell/data-shell/molecules

sort -n lengths

```

```{bash}

cd /home/shared/8TB_HDD_02/cnmntgna/GitHub/chris-coursework1/data/data-shell/data-shell/molecules

sort -n lengths > sorted-lengths
head -1 sorted-lengths

```

```{bash}

cd /home/shared/8TB_HDD_02/cnmntgna/GitHub/chris-coursework1/data/data-shell/data-shell/molecules

sort -n lengths | head -1

```

```{bash}

cd /home/shared/8TB_HDD_02/cnmntgna/GitHub/chris-coursework1/data/data-shell/data-shell/molecules

wc -l *.pdb | sort -n | head -1

```

```{bash}

cd /home/shared/8TB_HDD_02/cnmntgna/GitHub/chris-coursework1/data/data-shell/data-shell/north-pacific-gyre/2012-07-03

wc -l *.txt

```

```{bash}

cd /home/shared/8TB_HDD_02/cnmntgna/GitHub/chris-coursework1/data/data-shell/data-shell/north-pacific-gyre/2012-07-03

wc -l *.txt | sort -n | head -5

```

```{bash}

cd /home/shared/8TB_HDD_02/cnmntgna/GitHub/chris-coursework1/data/data-shell/data-shell/north-pacific-gyre/2012-07-03

wc -l *.txt | sort -n | tail -5

```

```{bash}

cd /home/shared/8TB_HDD_02/cnmntgna/GitHub/chris-coursework1/data/data-shell/data-shell/north-pacific-gyre/2012-07-03

ls *Z.txt

```
## End of assignment


