---
title: "CG Motifs"
author: "Chris Mantegna"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
  theme: cerulean
  highlight: 
    toc: true
    toc_float: true
    number_sections: true
    code_folding: show
    code_download: true
    callout-appearance: default
---
```{r setup, include=FALSE}

knitr::opts_chunk$set(
  highlight = TRUE,    # Highlight code
  echo = TRUE,         # Display code chunks
  eval = FALSE,        # Evaluate code chunks
  warning = TRUE,     # Hide warnings
  message = TRUE,     # Hide messages
  fig.width = 6,       # Set plot width in inches
  fig.height = 4,      # Set plot height in inches
  fig.align = "center" # Align plots to the center
  )

```

```{r}

getwd()

```
#convert my files from fastq to fasta
```{r}

library("ShortRead")

# Load the fastq file
fastq.file <- readFastq("/home/shared/8TB_HDD_02/cnmntgna/GitHub/chris-musselcon/output/ncbi/SRR19782039.fastq")

# Extract the sequences and convert to fasta format
sequences <- paste(sread(fastq.file), collapse="\n")
fasta <- paste(">seq\n", sequences, sep="")

# Write the fasta file
writeLines(fasta, "convertedFastq")

```

try to follow the assignment
```{r}
#install.packages("seqinr")
library(Biostrings)
library(seqinr)


input_file <- "fasta"
sequences <- read.fasta("/home/shared/8TB_HDD_02/cnmntgna/GitHub/chris-coursework1/assignment-code/convertedFastq")

``` 


```{r, eval=TRUE}

set.seed(42)

number_of_sequences_to_select <- 10

if (length(fasta) < number_of_sequences_to_select) {
  warning("There are fewer than 10 sequences in the fasta file. All sequences will be selected.")
  number_of_sequences_to_select <- length(sequences)
}

selected_indices <- sample(length(sequences), number_of_sequences_to_select)
selected_sequences <- sequences[selected_indices]

```


```{r}

output_file <- "../output/wishfulThinking.fasta"
write.fasta(selected_sequences, names(selected_sequences), output_file, open = "w")
```


```{bash}
#didn't use, happy for that!
#likely will not need; fix issue where gff and fa name did not match
# sed -i 's/>lcl|/>/g' ../output/10_seqs.fa
```


```{bash}

#needed downstream for IGV
/home/shared/samtools-1.12/samtools faidx \
../output/wishfulThinking.fasta
```


```{bash}
fuzznuc -sequence ../output/wishfulThinking.fasta -pattern CG -rformat gff -outfile ../output/CGoutput.gff
```

```

```{r, engine=bash}


```

```{r, engine=bash}


```

